config/routes.rb
InterfaceInput::Application.routes.draw do
  resources :currentpicks

  get "infiles/refresh"

  root :to => 'pages#home'
  resources :users, :user_sessions, :infile
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'home' => 'pages#home'
  match 'generate' => 'pages#generate'
  match 'print_log' => 'pages#print_log'

end

app/views/pages/generate.html.erb
<%#= form_for @user, :html => { :multipart => true } do |form| %>
<%# @user.infiles.build %>
<%#= form.submit "Save" %>
<%# end %>
<script type="text/javascript">

/***********************************************
* Disable "Enter" key in Form script- By Nurul Fadilah(nurul@REMOVETHISvolmedia.com)
* This notice must stay intact for use
* Visit http://www.dynamicdrive.com/ for full source code
***********************************************/


function handleEnter (field, event) {
  var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
  if (keyCode == 13) {
    var i;
    for (i = 0; i < field.form.elements.length; i++)
      if (field == field.form.elements[i])
        break;
      i = (i + 1) % field.form.elements.length;
      field.form.elements[i].focus();
      return false;
    } 
    else
      return true;
  }      

  </script>

<div id="left" style="width:500px;float:left;">

<hr>
<%#= link_to 'infile', users_path, :action => 'add_infile' %>
<%= form_for @user, :html => { :multipart => true } do |form_second| %>
<%# @user.infiles.build %>
<%= form_second.fields_for :infiles do |infile_fields| %>
<% if infile_fields.object.new_record? && (current_user.admin_flag == 1) %>
<p>
  <%= infile_fields.file_field :infile %>
   <%= submit_tag "Add file", :name => 'add_delete_infile' %>

</p>

<% end %>
<% end %>

<p>
<%= form_second.label :"New file" %>
    <%= form_second.text_field :newfilename, :onkeypress=>"return handleEnter(this, event)" %> 
    <%= submit_tag "New File", :name => 'new_file' %>
</p>

<% end %>
<hr>

<%= form_for @user, :html => { :multipart => true } do |form_again| %>
<%# @listOfInfiles = (Infile.select('infile_file_name')) %>
<%# logger.debug (@listOfInfiles) %>

<p>
  Select problem file: 
<%= select_tag "user[fileselected]", (options_for_select ([["Select", ""]]+@picker),@user.fileselected),{ :onchange => "this.form.submit();",:name => 'change_infile'}%>
<%= submit_tag "Delete Problem File", :confirm => 'Are you sure?', :name => 'delete_infile' %>

</p>

<%end%>

<%# @user = current_user %>
<%#= collection_select @user, @user.infiles.all, :id, :infile_file_name, {} %>
<%#= select_tag @theFile, @picker, @picker%>
<%# ,{ :onchange => "this.form.submit();"} %>

<%#= button_tag(:type => 'button') do %>
<%#= content_tag(:strong, 'Go!') %>
<%# logger.debug (@pickedFile) %>
<%# @test = "this is a test" %>
<%#= button_to 'Go!',  print_log_path(:pickedFile => @theFile) %>



  <%#= submit_tag "Change Problem File", :name => 'change_infile' %>



<%# logger.debug (@fnm) %>
<%# logger.debug ("hey") %>
<%# end %>

<hr>

<%= form_for @user, :html => { :multipart => true } do |form_again| %>

<%#= form_for @user do |form_first| %>

<%= select_tag "user[problemselectedstring]", (options_for_select ([["Select", ""]]+@picker2),@user.problemselectedstring)%>
<%# @user.problemchange = @user.problemselectedstring %>
<%#= collection_select(:user, :id, @picker2, :show, :show, {}, {:multiple => true}) %>
<p>
  <%= submit_tag "Select Problem", :name => 'first_button' %>
  <%= submit_tag "Add Problem", :name => 'add_problem_button', :disabled => @change_disabled %>
<%= submit_tag "Delete Problem", :confirm => 'Are you sure?', :name => 'delete_problem_button', :disabled => @change_disabled   %></p>


<% logger.debug (@user.problemselectedstring) %>
<%# logger.debug ("hey") %>
<%# logger.debug (@picker2.inspect) %>

<hr>

</div>

<div id="right" style="width:500px;float:right;">

<hr>
<%# end %>

<%#= form_for @user, :action => 'changeproblem', :html => { :multipart => true } do |form_fourth| %>


  <p>
    <%= form_again.label :"Change problem" %>
    <%= form_again.text_field :problemchange, :value => @user.problemselectedstring, :onkeypress=>"return handleEnter(this, event)" %> 
  </p>

  <% if @user.problemselectedstring && @user.problemselectedstring.length > 0 %>
  <% @change_disabled = false %>
  <% else %>
  <% @change_disabled = true %>
  <% end %>

  <%#= submit_tag "Change Problem", :name => 'second_button', :disabled => @change_disabled %>


  <hr>
  <p>
    <%= form_again.check_box :ExactCompleteMatch %> ExactCompleteMatch
    <%= form_again.check_box :ManualArithmetic %> ManualArithmetic
    <%= form_again.check_box :QuickElimination %> QuickElimination </p>
    <p>
    <%= form_again.check_box :ManualDone %> ManualDone 
    <%= form_again.check_box :Editable %> Editable 
    <%= form_again.check_box :ManualFactoring %> ManualFactoring </p>
    <p>
    <%= form_again.check_box :ManualTranspose %> ManualTranspose 
    <%= form_again.check_box :TapToFactorize %> TapToFactorize 
    <%= form_again.check_box :MoveComplex %> noMoveComplex </p>
    <p>
    <%= form_again.check_box :PlusSpacing %> noFactorize 
    <%= form_again.check_box :TimesSpacing %> TimesSpacing 
    <%= form_again.check_box :EqualsSpacing %> EqualsSpacing </p>
    <p>
    <%= form_again.check_box :Subtraction %> Subtraction 
    <%= form_again.check_box :GameTimeOut %> GameTimeOut 

  </p>
  
    <%#= submit_tag "Select Options", :name => 'third_button', :disabled => @change_disabled %>
  
  <hr>
<p>
  <%= form_again.label :"Accuracy coins" %>
  <%= form_again.text_field :accuracycoins, :size => 5, :value => @user.accuracycoins, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_again.label :"Min errors" %>
  <%= form_again.text_field :minerrors, :size => 5, :value => @user.minerrors, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_again.label :"Max errors" %>
  <%= form_again.text_field :maxerrors, :size => 5, :value => @user.maxerrors, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_again.label :"Speed coins" %>
  <%= form_again.text_field :speedcoins, :size => 5, :value => @user.speedcoins, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_again.label :"Min speed" %>
  <%= form_again.text_field :minspeed, :size => 5, :value => @user.minspeed, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_again.label :"Max speed" %>
  <%= form_again.text_field :maxspeed, :size => 5, :value => @user.maxspeed, :onkeypress=>"return handleEnter(this, event)" %> 
</p>

  <p><%= submit_tag "Change problem", :name => 'fourth_button', :disabled => @change_disabled %></p>

 <hr>
</div>
<% end %>

app/views/pages/generate_bak.html.erb
<%#= link_to 'infile', users_path, :action => 'add_infile' %>
<hr>
<%= form_for @user, :html => { :multipart => true } do |form_first| %>
<%# @listOfInfiles = (Infile.select('infile_file_name')) %>
<%# logger.debug (@listOfInfiles) %>
<%= select_tag "user[fileselected]", (options_for_select ([["Select", ""]]+@picker),@user.fileselected)%>
<%# @user = current_user %>
<%#= collection_select @user, @user.infiles.all, :id, :infile_file_name, {} %>
<%#= select_tag @theFile, @picker, @picker%>
<%# ,{ :onchange => "this.form.submit();"} %>

<%#= button_tag(:type => 'button') do %>
<%#= content_tag(:strong, 'Go!') %>
<%# logger.debug (@pickedFile) %>
<%# @test = "this is a test" %>
<%#= button_to 'Go!',  print_log_path(:pickedFile => @theFile) %>

<p><%= form_first.submit %></p>
<%# logger.debug (@fnm) %>
<%# logger.debug ("hey") %>
<% end %>

<hr>

<%= form_for @user, :html => { :multipart => true } do |form| %>
<%# @user.infiles.build %>
<%#= form.submit "Save" %>
<%# end %>


<%= form.fields_for :infiles do |infile_fields| %>
<% if infile_fields.object.new_record? %>
<p>
  <%= infile_fields.file_field :infile %>
</p>
<% else %>
<p><%= infile_fields.object.infile_file_name %>  
  <%= infile_fields.check_box :_destroy %> delete
</p>
<% end %>
<% end %>
<p><%= form.submit %></p>

<hr>

<%#= form_for @user, :html => { :multipart => true } do |form_third| %>

<%= form_for @user do |form_third| %>

<%= select_tag "user[problemselectedstring]", (options_for_select ([["Select", ""]]+@picker2),@user.problemselectedstring)%>
<%# @user.problemchange = @user.problemselectedstring %>
<%#= collection_select(:user, :id, @picker2, :show, :show, {}, {:multiple => true}) %>
<p>
  <%= submit_tag "Select Problem", :name => 'first_button' %>
</p>
<% logger.debug (@user.problemselectedstring) %>
<%# logger.debug ("hey") %>
<%# logger.debug (@picker2.inspect) %>

<hr>


<%# end %>

<%#= form_for @user, :action => 'changeproblem', :html => { :multipart => true } do |form_fourth| %>

<script type="text/javascript">

/***********************************************
* Disable "Enter" key in Form script- By Nurul Fadilah(nurul@REMOVETHISvolmedia.com)
* This notice must stay intact for use
* Visit http://www.dynamicdrive.com/ for full source code
***********************************************/

function handleEnter (field, event) {
  var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
  if (keyCode == 13) {
    var i;
    for (i = 0; i < field.form.elements.length; i++)
      if (field == field.form.elements[i])
        break;
      i = (i + 1) % field.form.elements.length;
      field.form.elements[i].focus();
      return false;
    } 
    else
      return true;
  }      

  </script>

  <p>
    <%= form_third.label :"Change problem" %>
    <%= form_third.text_field :problemchange, :value => @user.problemselectedstring, :onkeypress=>"return handleEnter(this, event)" %> 
  </p>

  <% if @user.problemselectedstring.length > 0 %>
  <% @change_disabled = false %>
  <% else %>
  <% @change_disabled = true %>
  <% end %>

  <p><%= submit_tag "Change Problem", :name => 'second_button', :disabled => @change_disabled %></p>


  <hr>
  <p>
    <%= form_third.check_box :ExactCompleteMatch %> ExactCompleteMatch
    <%= form_third.check_box :ManualArithmetic %> ManualArithmetic
    <%= form_third.check_box :QuickElimination %> QuickElimination 
    <%= form_third.check_box :ManualDone %> ManualDone 
    <%= form_third.check_box :Editable %> Editable 
    <%= form_third.check_box :ManualFactoring %> ManualFactoring 
    <%= form_third.check_box :ManualTranspose %> ManualTranspose 
    <%= form_third.check_box :TapToFactorize %> TapToFactorize 
    <%= form_third.check_box :MoveComplex %> MoveComplex 
    <%= form_third.check_box :PlusSpacing %> PlusSpacing 
    <%= form_third.check_box :TimesSpacing %> TimesSpacing 
    <%= form_third.check_box :EqualsSpacing %> EqualsSpacing 
    <%= form_third.check_box :Subtraction %> Subtraction 
    <%= form_third.check_box :GameTimeOut %> GameTimeOut 


  </p>
  <p>
    <%= submit_tag "Select Options", :name => 'third_button', :disabled => @change_disabled %>
  </p>
  <hr>
<p>
  <%= form_third.label :"Change accuracy coins" %>
  <%= form_third.text_field :accuracycoins, :value => @user.accuracycoins, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_third.label :"Change min errors" %>
  <%= form_third.text_field :minerrors, :value => @user.minerrors, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_third.label :"Change max errors" %>
  <%= form_third.text_field :maxerrors, :value => @user.maxerrors, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_third.label :"Change speed coins" %>
  <%= form_third.text_field :speedcoins, :value => @user.speedcoins, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_third.label :"Change min speed" %>
  <%= form_third.text_field :minspeed, :value => @user.minspeed, :onkeypress=>"return handleEnter(this, event)" %> 
</p>
<p>
  <%= form_third.label :"Change max speed" %>
  <%= form_third.text_field :maxspeed, :value => @user.maxspeed, :onkeypress=>"return handleEnter(this, event)" %> 
</p>

  


  <p><%= submit_tag "Change vaule and speed", :name => 'fourth_button', :disabled => @change_disabled %></p>


  <%end%>  
  <% end %>

app/views/pages/home.html.erb
<h1>Welcome to grasping math / algebra touch input file generator.</h1>

<p id="notice"><%= notice %></p>

<p>A link to a demo of grasping math should go here.</p>


<% if (current_user&&current_user.admin_flag == 1) %>
  <p><%= link_to 'users', users_path %></p>
<% end %>

<p>
	<% if current_user %>
	<%= link_to 'generate', generate_path %>
	<% end %>
</p>